Repository jenkinsci/ec2-plugin, pull requests merged in 2019-10, with the labels that each got.

#389 Use non-deprecated code and remove unused imports
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/main/java/hudson/plugins/ec2/EC2PrivateKey.java
  src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
  src/main/java/hudson/plugins/ec2/EC2Step.java
  src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
  src/main/java/hudson/plugins/ec2/ssh/HostKeyVerifierImpl.java
  src/main/java/hudson/plugins/ec2/win/WinConnection.java
  src/main/java/hudson/plugins/ec2/win/winrm/NegotiateNTLMSchemaFactory.java
  src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/EC2StepTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
  src/test/java/hudson/plugins/ec2/ssh/HostKeyVerifierImplTest.java
Labels: chore

#356 Use filter query when describing instances
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
Labels: enhancement

#399 [JENKINS-57795] Retry when waking up orphans or creating new nodes
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
Labels: bugfix
