Repository jenkinsci/ec2-plugin, pull requests merged in 2019-12, with the labels that each got.

#382 Allow defining node properties on template
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
Labels: enhancement

#419 Move documentation to github
  CHANGELOG.md
  README.md
  docs/images/ami.png
  docs/images/cloud.png
  docs/images/init-scripts.png
  pom.xml
Labels: documentation

#418 [JENKINS-59633] delete new lines in encrypted windows password
  src/main/java/hudson/plugins/ec2/EC2PrivateKey.java
  src/test/java/hudson/plugins/ec2/EC2PrivateKeyTest.java
Labels: bugfix

#404 Support limiting minimum instances to a time range
  src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/main/java/hudson/plugins/ec2/util/MinimumInstanceChecker.java
  src/main/java/hudson/plugins/ec2/util/MinimumNumberOfInstancesTimeRangeConfig.java
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-minimumNumberOfInstancesTimeRangeConfig.html
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Labels: enhancement
