Repository jenkinsci/ec2-plugin, pull requests merged in 2020-05, with the labels that each got.

#454 Fix CI Errors
  pom.xml
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudUnitTest.java
  src/test/java/hudson/plugins/ec2/EC2HostAddressProviderTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Labels: chore

#457 Use common-compress from core
  pom.xml
Labels: chore

#455 StrictHostKeyChecking=off should be StrictHostKeyChecking=no
  src/main/java/hudson/plugins/ec2/HostKeyVerificationStrategyEnum.java
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-hostKeyVerificationStrategy.html
Labels: regression

#461 [JENKINS-62227] Replace slf4j by java logging in CloudHelper
  src/main/java/hudson/plugins/ec2/CloudHelper.java
Labels: bugfix

#458 [JENKINS-62090] Specify SGs only on 1 part of request
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Labels: regression

#465 Be explicit about build configurations
  Jenkinsfile
Labels: chore

#464 [JENKINS-62231] Move start logic to postInitialize to avoid OldDataMo…
  src/main/java/hudson/plugins/ec2/PluginImpl.java
Labels: bugfix

#466 Fix toc because of downgrade issue
  README.md
Labels: documentation
