Repository jenkinsci/ec2-plugin, pull requests merged in 2020-11, with the labels that each got.

#456 JENKINS-62212 Add filter to periodic EC2 connection polling
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
Labels: enhancement

#524 Change parameter for MaxMemoryPerShellMB to 10GB
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-amiType.html
Labels: documentation

#520 Use SSHUserPrivateKey instead of BasicSSHUserPrivateKey
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
  src/test/java/hudson/plugins/ec2/util/TestSSHUserPrivateKey.java
Labels: bugfix, enhancement

#473 WinRM Connection Pooling implementation
  src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
  src/main/java/hudson/plugins/ec2/win/winrm/WinRMConnectionManagerFactory.java
Labels: enhancement

#528 [JENKINS-64147] Forwards compat with table-to-div
  src/main/resources/hudson/plugins/ec2/EC2Tag/config.jelly
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
  src/main/resources/lib/ec2/blockWrapper.jelly
  src/main/resources/lib/ec2/taglib
Labels: bugfix

#533 [JENKINS-59180] Allow AMI filtering instead of AMI ID
  src/main/java/hudson/plugins/ec2/EC2Filter.java
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/main/resources/hudson/plugins/ec2/EC2Filter/config.jelly
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-ami.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-amiFilters.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-amiOwners.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-amiUsers.html
  src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
  src/test/java/hudson/plugins/ec2/EC2FilterTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
  src/test/resources/hudson/plugins/ec2/Ami.yml
Labels: enhancement

#538 [JENKINS-61161] Avoid infamous UI connection strategy warning
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Labels: bugfix
