Repository jenkinsci/ec2-plugin, pull requests merged in 2021-05, with the labels that each got.

#607 [JENKINS-65398] Terminology update
  README.md
  src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/main/java/hudson/plugins/ec2/EC2Computer.java
  src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
  src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
  src/main/java/hudson/plugins/ec2/EC2SlaveMonitor.java
  src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
  src/main/java/hudson/plugins/ec2/EC2Tag.java
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/main/java/hudson/plugins/ec2/ssh/EC2MacLauncher.java
  src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
  src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
  src/main/java/hudson/plugins/ec2/win/WinConnection.java
  src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/help-region.html
  src/main/resources/hudson/plugins/ec2/EC2Cloud/config.jelly
  src/main/resources/hudson/plugins/ec2/EC2Cloud/help-useInstanceProfileForCredentials.html
  src/main/resources/hudson/plugins/ec2/EC2Computer/help-idleTerminationMinutes.html
  src/main/resources/hudson/plugins/ec2/EC2Computer/help-usePrivateDnsName.html
  src/main/resources/hudson/plugins/ec2/EC2Slave/help-idleTerminationMinutes.html
  src/main/resources/hudson/plugins/ec2/EC2Slave/help-stopOnTerminate.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-amiType.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-connectBySSHProcess.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-description.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-idleTerminationMinutes.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-initScript.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-launchTimeoutStr.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-maxTotalUses.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-stopOnTerminate.html
  src/main/resources/hudson/plugins/ec2/UnixData/config.jelly
  src/main/resources/hudson/plugins/ec2/WindowsData/help-bootDelay.html
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Labels: documentation

#608 [JENKINS-64738] Fixed typo in dropdownListBlock attribute name
  src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
Labels: bugfix

#615 Add required library to project configuration
  pom.xml
  src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
Labels: chore

#612 [JENKINS-64738] Fixed reference to get the amiType class name
  src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
Labels: bugfix
