Repository jenkinsci/ec2-plugin, pull requests merged in 2021-06, with the labels that each got.

#620 Script security version fix
  pom.xml
Labels: chore

#625 Enable device mapping tests
  src/test/java/hudson/plugins/ec2/util/DeviceMappingParserTest.java
Labels: chore

#617 Raise an exception when AMI search is blank.
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
Labels: bugfix

#626 Fix connection strategy warning for new templates
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Labels: bugfix

#624 [JENKINS-65569] Prevent invalid names for agents
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Labels: bugfix

#627 Fix connection strategy UI prompt
  src/main/java/hudson/plugins/ec2/ConnectionStrategy.java
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Labels: regression

#621 [JENKINS-64569] Add support for EBS Throughput parameter
  src/main/java/hudson/plugins/ec2/util/DeviceMappingParser.java
  src/test/java/hudson/plugins/ec2/util/DeviceMappingParserTest.java
Labels: enhancement

#628 Cleanup tests and improve build times
  pom.xml
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/main/java/hudson/plugins/ec2/UnixData.java
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudUnitTest.java
  src/test/java/hudson/plugins/ec2/AmazonPartitionEC2CloudTest.java
  src/test/java/hudson/plugins/ec2/EC2InstanceTypesTest.java
  src/test/java/hudson/plugins/ec2/EC2OndemandSlaveTest.java
  src/test/java/hudson/plugins/ec2/EC2PrivateKeyTest.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/EC2StepTest.java
  src/test/java/hudson/plugins/ec2/ListRegions.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
  src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
  src/test/java/hudson/plugins/ec2/util/PluginTestRule.java
Labels: chore

#630 Set SecurityProvider for SMB
  src/main/java/hudson/plugins/ec2/win/WinConnection.java
Labels: regression

#632 [JENKINS-23792] Do not terminate stopped EC2 nodes that were just booted
  src/main/java/hudson/plugins/ec2/EC2Computer.java
  src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
Labels: bugfix
