Repository jenkinsci/ec2-plugin, pull requests merged in 2021-10, with the labels that each got.

#663 update aws-sdk to 11.12.70
  pom.xml
Labels: dependencies

#667 doc: add docs for throughput parameter
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-customDeviceMapping.html
Labels: documentation

#666 win: cleanup workaround for smbj
  src/main/java/hudson/plugins/ec2/win/WinConnection.java
Labels: chore

#665 [JENKINS-66736] win: retry connection on transportexception
  src/main/java/hudson/plugins/ec2/win/WinConnection.java
Labels: bugfix

#664 win: cleanup some windows warnings and deprecated code
  src/main/java/hudson/plugins/ec2/win/winrm/WinRM.java
  src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
  src/main/java/hudson/plugins/ec2/win/winrm/WinRMConnectionManagerFactory.java
Labels: chore

#662 Replace heavyweight aws-java-sdk with fine-grained plugin
  pom.xml
Labels: enhancement
