Repository jenkinsci/ec2-plugin, pull requests merged in 2021-04, with the labels that each got.

#492 Add Support for Host Tenancy Option
  README.md
  src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
  src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
  src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/main/java/hudson/plugins/ec2/Tenancy.java
  src/main/java/hudson/plugins/ec2/util/EC2AgentConfig.java
  src/main/java/hudson/plugins/ec2/util/EC2AgentFactoryImpl.java
  src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-tenancy.html
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/java/hudson/plugins/ec2/util/EC2AgentFactoryMockImpl.java
  src/test/resources/hudson/plugins/ec2/UnixDataExport-withAltEndpoint.yml
  src/test/resources/hudson/plugins/ec2/UnixDataExport.yml
Labels: enhancement

#515 Add retry logic for connection timeout exception
  src/main/java/hudson/plugins/ec2/CloudHelper.java
  src/test/java/hudson/plugins/ec2/CloudHelperTest.java
Labels: bugfix

#591 [JENKINS-60647] Fix JCasC for minimumNumberOfInstancesTimeRangeConfig
  src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
  src/main/java/hudson/plugins/ec2/util/MinimumInstanceChecker.java
  src/main/java/hudson/plugins/ec2/util/MinimumNumberOfInstancesTimeRangeConfig.java
  src/main/resources/hudson/plugins/ec2/EC2Cloud/help-sshKeysCredentialsId.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
  src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/resources/hudson/plugins/ec2/Unix-withMinimumInstancesTimeRange.yml
Labels: enhancement

#595 SSH key check is too strict
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
Labels: bugfix

#590 [JENKINS-64520][JENKINS-62340] Pass ssh host key to ssh process when using the strategy CHECK_NEW_HARD
  src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
Labels: enhancement

#597 Fallback on other templates if provisioning fails
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
Labels: enhancement

#603 Removed usage of Guava
  src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
  src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
  src/main/java/hudson/plugins/ec2/win/winrm/request/ExecuteCommandRequest.java
  src/main/java/hudson/plugins/ec2/win/winrm/request/OpenShellRequest.java
  src/main/java/hudson/plugins/ec2/win/winrm/soap/Header.java
  src/main/java/hudson/plugins/ec2/win/winrm/soap/HeaderBuilder.java
  src/main/java/hudson/plugins/ec2/win/winrm/soap/Namespaces.java
Labels: chore

#602 Fill credentials from current context instead of just Jenkins singleton
  src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/main/java/hudson/plugins/ec2/Eucalyptus.java
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
Labels: enhancement

#605 [JENKINS-64571] Fall back to on demand provisioning when spot quota exceeded and option set
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Labels: enhancement
