Repository jenkinsci/ec2-plugin, pull requests merged in 2022-08, with the labels that each got.

#771 Remove PowerMock
  .mvn/extensions.xml
  pom.xml
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudUnitTest.java
  src/test/java/hudson/plugins/ec2/CloudHelperTest.java
  src/test/java/hudson/plugins/ec2/EC2CloudTest.java
  src/test/java/hudson/plugins/ec2/EC2StepTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
Labels: chore

#748 [Documentation][Security] Enforce IMDSv2 by default & update groovy section to use up-to-date constructor
  README.md
  src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-metadataTokensRequired.html
Labels: enhancement, documentation

#772 Test with java 17
  Jenkinsfile
Labels: chore

#768 [JENKINS-69399] Prevent offlining ec2 node if jobs in node queue
  src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
Labels: enhancement

#766 [JENKINS-69304] Allow specifying a java path
  README.md
  src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
  src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
  src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/main/java/hudson/plugins/ec2/ssh/EC2MacLauncher.java
  src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
  src/main/java/hudson/plugins/ec2/util/EC2AgentConfig.java
  src/main/java/hudson/plugins/ec2/util/EC2AgentFactoryImpl.java
  src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
  src/main/resources/hudson/plugins/ec2/EC2Cloud/help-javaPath.html
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
  src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
  src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/java/hudson/plugins/ec2/util/EC2AgentFactoryMockImpl.java
  src/test/resources/hudson/plugins/ec2/MacDataExport.yml
  src/test/resources/hudson/plugins/ec2/UnixData-withAltEndpointAndJavaPath.yml
  src/test/resources/hudson/plugins/ec2/UnixDataExport-withAltEndpointAndJavaPath.yml
  src/test/resources/hudson/plugins/ec2/UnixDataExport.yml
Labels: enhancement
