Repository jenkinsci/ec2-plugin, pull requests merged in 2023-09, with the labels that each got.

#887 Update aws sdk to 1.12.529-406.vdeff15e5817d
  pom.xml
Labels: dependencies

#850 Created method that would allow to programmatically add new slave templates to an EC2Cloud
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/test/java/hudson/plugins/ec2/EC2CloudTest.java
Labels: enhancement

#886 JENKINS-71554: Reconnect on "RequestExpired" exception
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
Labels: bugfix

#875 Test support for cloud management changes
  pom.xml
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
  src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
  src/test/java/hudson/plugins/ec2/EucalyptusTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/resources/hudson/plugins/ec2/EC2CloudEmpty.yml
Labels: dependencies

#892 [JENKINS-71737] rename cloudName to name
  README.md
  pom.xml
  src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
  src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
  src/test/resources/hudson/plugins/ec2/Ami.yml
  src/test/resources/hudson/plugins/ec2/BackwardsCompatibleConnectionStrategy.yml
  src/test/resources/hudson/plugins/ec2/EC2CloudEmpty.yml
  src/test/resources/hudson/plugins/ec2/Mac.yml
  src/test/resources/hudson/plugins/ec2/MacData.yml
  src/test/resources/hudson/plugins/ec2/MacDataExport.yml
  src/test/resources/hudson/plugins/ec2/Unix-withMinimumInstancesTimeRange.yml
  src/test/resources/hudson/plugins/ec2/Unix.yml
  src/test/resources/hudson/plugins/ec2/UnixData-withAltEndpointAndJavaPath.yml
  src/test/resources/hudson/plugins/ec2/UnixData.yml
  src/test/resources/hudson/plugins/ec2/UnixDataExport-withAltEndpointAndJavaPath.yml
  src/test/resources/hudson/plugins/ec2/UnixDataExport.yml
  src/test/resources/hudson/plugins/ec2/WindowsData.yml
Labels: breaking
