Repository jenkinsci/ec2-plugin, pull requests merged in 2023-04, with the labels that each got.

#827 Remove cloudId and use the name entered by the user directly.
  src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
  src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
Labels: chore

#830 pom: update aws-sdk and fix upper dep error
  pom.xml
Labels: dependencies

#831 pom: update plugin-pom to 4.58
  pom.xml
Labels: dependencies

#837 Adds support for custom name for Eucalyptus. Also fixes roundtrip for ec2Endpoint and s3Endpoint
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/main/java/hudson/plugins/ec2/Eucalyptus.java
  src/main/resources/hudson/plugins/ec2/Eucalyptus/config-entries.jelly
  src/test/java/hudson/plugins/ec2/EucalyptusTest.java
Labels: bugfix
