Repository jenkinsci/ec2-plugin, pull requests merged in 2024-12, with the labels that each got.

#1016 [JENKINS-74945] Use Role ARN when defined
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
  src/main/resources/hudson/plugins/ec2/EC2Cloud/help-roleArn.html
  src/main/resources/hudson/plugins/ec2/EC2Cloud/help-roleSessionName.html
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
Labels: enhancement

#1023 Remove usages of deprecated constructors in tests
  src/test/java/hudson/plugins/ec2/EC2CloudTest.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/EC2SlaveMonitorTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
  src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
  src/test/java/hudson/plugins/ec2/ssh/verifiers/SshHostKeyVerificationStrategyTest.java
Labels: test

#1024 Remove more usages of deprecated constructors in tests
  src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
  src/test/java/hudson/plugins/ec2/EC2OndemandSlaveTest.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
  src/test/java/hudson/plugins/ec2/ssh/verifiers/SshHostKeyVerificationStrategyTest.java
  src/test/java/hudson/plugins/ec2/win/WinConnectionTest.java
Labels: test

#1026 Migrate from Acegi compatibility layer to Spring Security
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
Labels: internal

#1027 Remove Eucalyptus support
  README.md
  src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
  src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/main/java/hudson/plugins/ec2/EC2Step.java
  src/main/java/hudson/plugins/ec2/Eucalyptus.java
  src/main/java/hudson/plugins/ec2/NoDelayProvisionerStrategy.java
  src/main/java/hudson/plugins/ec2/PluginImpl.java
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/main/java/hudson/plugins/ec2/SpotConfiguration.java
  src/main/resources/hudson/plugins/ec2/EC2Cloud/config-entries.jelly
  src/main/resources/hudson/plugins/ec2/EC2Cloud/help-ec2EndpointUrl.html
  src/main/resources/hudson/plugins/ec2/EC2Cloud/help-noDelayProvisioning.html
  src/main/resources/hudson/plugins/ec2/EC2Cloud/help-region.html
  src/main/resources/hudson/plugins/ec2/EC2Cloud/help-s3EndpointUrl.html
  src/main/resources/hudson/plugins/ec2/Eucalyptus/config-entries.jelly
  src/main/resources/hudson/plugins/ec2/Eucalyptus/help-url.html
  src/main/resources/hudson/plugins/ec2/Messages.properties
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
  src/test/java/hudson/plugins/ec2/AmazonEC2CloudUnitTest.java
  src/test/java/hudson/plugins/ec2/CloudHelperTest.java
  src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
  src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
  src/test/java/hudson/plugins/ec2/EC2CloudTest.java
  src/test/java/hudson/plugins/ec2/EC2CloudUnitTest.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/EC2SlaveMonitorTest.java
  src/test/java/hudson/plugins/ec2/EC2StepTest.java
  src/test/java/hudson/plugins/ec2/EucalyptusTest.java
  src/test/java/hudson/plugins/ec2/FileBasedSSHKeyTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
  src/test/java/hudson/plugins/ec2/util/AmazonEC2FactoryMockImpl.java
Labels: removed
