Repository jenkinsci/ec2-plugin, pull requests merged in 2024-11, with the labels that each got.

#995 Added tagging for Instance Network Interface
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Labels: enhancement

#997 Replace dropdown button to remove dependency on YUI
  pom.xml
  src/main/resources/hudson/plugins/ec2/EC2Cloud/computerSet.jelly
  src/main/resources/hudson/plugins/ec2/EC2Cloud/provision.js
Labels: enhancement

#1001 Update jenkins baseline to 2.452.4
  pom.xml
Labels: chore

#999 Adding FINE logging in SG lookups for easier troubleshooting
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Labels: enhancement

#1008 Reconnect to EC2 also when error code is ExpiredToken
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
Labels: bugfix

#1013 Fix Spotless
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
Labels: skip-changelog
