Repository jenkinsci/ec2-plugin, pull requests merged in 2025-08, with the labels that each got.

#1127 Simplification to `SSHCredentialHelper`
  src/test/java/hudson/plugins/ec2/util/SSHCredentialHelper.java
Labels: chore

#1126 Fail `getEC2HostAddress` for a terminated instance
  src/main/java/hudson/plugins/ec2/ssh/EC2SSHLauncher.java
  src/test/java/hudson/plugins/ec2/ssh/InitScriptExecutionTest.java
Labels: bugfix

#1124 Call `MinimumInstanceChecker` when an agent is bound
  src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
Labels: bugfix

#1134 [JENKINS-76021] Fix non proxy hosts support
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
Labels: bug

#1125 Discard idle instances during shutdown
  src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
  src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
  src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/main/java/hudson/plugins/ec2/util/MinimumInstanceChecker.java
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
  src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-terminateIdleDuringShutdown.html
  src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/MockEC2Computer.java
  src/test/java/hudson/plugins/ec2/ssh/InitScriptExecutionTest.java
Labels: enhancement
