Repository jenkinsci/ec2-plugin, pull requests merged in 2025-03, with the labels that each got.

#1048 [JENKINS-75214] Added prioritization of SSH host key algorithms
  src/main/java/hudson/plugins/ec2/ssh/EC2MacLauncher.java
  src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
  src/main/java/hudson/plugins/ec2/util/KeyHelper.java
  src/main/java/hudson/plugins/ec2/util/SSHClientHelper.java
  src/test/java/hudson/plugins/ec2/MockEC2Computer.java
  src/test/java/hudson/plugins/ec2/ssh/verifiers/SshHostKeyVerificationStrategyTest.java
  src/test/java/hudson/plugins/ec2/util/SSHClientHelperTest.java
  src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp256/config.xml
  src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp256/nodes/MockInstanceForTestHostKey/ssh-host-key.xml
  src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp384/config.xml
  src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp384/nodes/MockInstanceForTestHostKey/ssh-host-key.xml
  src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp521/config.xml
  src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp521/nodes/MockInstanceForTestHostKey/ssh-host-key.xml
  src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ed25519/config.xml
  src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ed25519/nodes/MockInstanceForTestHostKey/ssh-host-key.xml
  src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/setupSshClientWithNoHostKey/config.xml
Labels: bugfix, bug

#1044 Remove deprecations and use Java 17 language features
  src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/main/java/hudson/plugins/ec2/EC2Computer.java
  src/main/java/hudson/plugins/ec2/EC2ComputerLauncher.java
  src/main/java/hudson/plugins/ec2/EC2PrivateKey.java
  src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
  src/main/java/hudson/plugins/ec2/EC2SlaveMonitor.java
  src/main/java/hudson/plugins/ec2/EC2Step.java
  src/main/java/hudson/plugins/ec2/NoDelayProvisionerStrategy.java
  src/main/java/hudson/plugins/ec2/SpotConfiguration.java
  src/main/java/hudson/plugins/ec2/ssh/EC2MacLauncher.java
  src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
  src/main/java/hudson/plugins/ec2/ssh/HostKeyVerifierImpl.java
  src/main/java/hudson/plugins/ec2/ssh/verifiers/HostKey.java
  src/main/java/hudson/plugins/ec2/util/AmazonEC2FactoryImpl.java
  src/main/java/hudson/plugins/ec2/util/FIPS140Utils.java
  src/main/java/hudson/plugins/ec2/util/KeyHelper.java
  src/main/java/hudson/plugins/ec2/util/MinimumInstanceChecker.java
  src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
  src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
  src/main/java/hudson/plugins/ec2/win/winrm/soap/Header.java
  src/main/java/hudson/plugins/ec2/win/winrm/soap/HeaderBuilder.java
  src/test/java/hudson/plugins/ec2/EC2CloudUnitTest.java
  src/test/java/hudson/plugins/ec2/EC2FilterTest.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/FileBasedSSHKeyTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
  src/test/java/hudson/plugins/ec2/util/ConnectionRule.java
  src/test/java/hudson/plugins/ec2/util/EC2AgentFactoryMockImpl.java
  src/test/java/hudson/plugins/ec2/win/WinConnectionTest.java
Labels: internal

#1055 Partial revert of #1044
  src/main/java/hudson/plugins/ec2/util/AmazonEC2FactoryImpl.java
Labels: bug

#1059 Do not allow Win NTLM connections in FIPS mode
  src/main/java/hudson/plugins/ec2/win/WinConnection.java
  src/main/resources/hudson/plugins/ec2/Messages.properties
  src/test/java/hudson/plugins/ec2/win/WinConnectionWithFIPSTest.java
Labels: bugfix, bug

#1063 [JENKINS-75491] Add Instance Id to getDecodedConsoleOutputResponse
  src/main/java/hudson/plugins/ec2/EC2Computer.java
Labels: bugfix
