Repository jenkinsci/ec2-plugin, pull requests merged in 2025-04, with the labels that each got.

#1065 Reduce usage of AWS SDK for Java v1 from compatibility layer
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/main/java/hudson/plugins/ec2/util/InstanceTypeCompat.java
Labels: internal

#1071 add default for enclaveEnabled in readResolve()
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Labels: bugfix

#1073 Prevent launching of ec2 nodes on init script failure
  src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
  src/test/java/hudson/plugins/ec2/ssh/InitScriptExecutionTest.java
Labels: bugfix

#1076 Migrate tests to JUnit5
  pom.xml
  src/test/java/hudson/plugins/ec2/CloudHelperTest.java
  src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
  src/test/java/hudson/plugins/ec2/ConnectionStrategyTest.java
  src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
  src/test/java/hudson/plugins/ec2/EC2CloudMigrationTest.java
  src/test/java/hudson/plugins/ec2/EC2CloudPrivateKeyWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/EC2CloudPrivateKeyWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/EC2CloudTest.java
  src/test/java/hudson/plugins/ec2/EC2CloudUnitTest.java
  src/test/java/hudson/plugins/ec2/EC2FilterTest.java
  src/test/java/hudson/plugins/ec2/EC2HostAddressProviderTest.java
  src/test/java/hudson/plugins/ec2/EC2OndemandSlaveTest.java
  src/test/java/hudson/plugins/ec2/EC2PrivateKeyTest.java
  src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
  src/test/java/hudson/plugins/ec2/EC2SlaveMonitorTest.java
  src/test/java/hudson/plugins/ec2/EC2StepTest.java
  src/test/java/hudson/plugins/ec2/FileBasedSSHKeyTest.java
  src/test/java/hudson/plugins/ec2/HostKeyTest.java
  src/test/java/hudson/plugins/ec2/HostKeyWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/HostKeyWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
  src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
  src/test/java/hudson/plugins/ec2/WinRMMessageTest.java
  src/test/java/hudson/plugins/ec2/WindowsDataWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/WindowsDataWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/ssh/HostKeyVerifierImplTest.java
  src/test/java/hudson/plugins/ec2/ssh/InitScriptExecutionTest.java
  src/test/java/hudson/plugins/ec2/ssh/verifiers/SshHostKeyVerificationStrategyTest.java
  src/test/java/hudson/plugins/ec2/util/ConnectionExtension.java
  src/test/java/hudson/plugins/ec2/util/ConnectionRule.java
  src/test/java/hudson/plugins/ec2/util/DeviceMappingParserTest.java
  src/test/java/hudson/plugins/ec2/util/FIPS140UtilsWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/util/FIPS140UtilsWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/util/KeyHelperPublicKeyTest.java
  src/test/java/hudson/plugins/ec2/util/KeyHelperSSHAlgorithmTest.java
  src/test/java/hudson/plugins/ec2/util/KeyHelperTestHelper.java
  src/test/java/hudson/plugins/ec2/util/SSHClientHelperTest.java
  src/test/java/hudson/plugins/ec2/win/WinConnectionTest.java
  src/test/java/hudson/plugins/ec2/win/WinConnectionWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/WinConnectionWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/winrm/WinRMClientWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/winrm/WinRMClientWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/winrm/WinRMWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/winrm/WinRMWithoutFIPSTest.java
Labels: test

#1078 [JENKINS-75589] Region is no longer being kept in the UI
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/test/java/hudson/plugins/ec2/EC2CloudUnitTest.java
Labels: bug
