Repository jenkinsci/ec2-plugin, pull requests merged in 2025-01, with the labels that each got.

#1030 Remove `ZpoolMonitor` and `ZPoolExpandNotice`
  pom.xml
  src/main/java/hudson/plugins/ec2/ebs/ZPoolExpandNotice.java
  src/main/java/hudson/plugins/ec2/ebs/ZPoolMonitor.java
  src/main/resources/hudson/plugins/ec2/ebs/Messages.properties
  src/main/resources/hudson/plugins/ec2/ebs/ZPoolExpandNotice/index.jelly
  src/main/resources/hudson/plugins/ec2/ebs/ZPoolExpandNotice/message.jelly
Labels: removed

#1031 Update pom.xml to match archetype and use `jenkins.baseline` property to keep bom in sync
  pom.xml
Labels: chore

#1032 JENKINS-75098:Log EC2 errors while calling RunInstances for reserved capacity
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
  src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Labels: enhancement

#1033 Update log message from EC2 RunInstances call to include number of nodes requested
  src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Labels: enhancement

#1041 [JENKINS-75187] Unable to Connect to Agents
  src/main/java/hudson/plugins/ec2/ssh/EC2MacLauncher.java
  src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
Labels: bugfix, bug

#1010 [JENKINS-74907] Add validations when Jenkins is in FIPS mode
  pom.xml
  src/main/java/hudson/plugins/ec2/EC2Cloud.java
  src/main/java/hudson/plugins/ec2/WindowsData.java
  src/main/java/hudson/plugins/ec2/ssh/verifiers/HostKey.java
  src/main/java/hudson/plugins/ec2/util/FIPS140Utils.java
  src/main/java/hudson/plugins/ec2/util/KeyHelper.java
  src/main/java/hudson/plugins/ec2/win/WinConnection.java
  src/main/java/hudson/plugins/ec2/win/winrm/WinRM.java
  src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
  src/main/resources/hudson/plugins/ec2/Messages.properties
  src/test/java/hudson/plugins/ec2/EC2CloudPrivateKeyWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/EC2CloudPrivateKeyWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/HostKeyWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/HostKeyWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/WindowsDataWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/WindowsDataWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/util/FIPS140UtilsWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/util/FIPS140UtilsWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/WinConnectionWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/WinConnectionWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/winrm/WinRMClientWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/winrm/WinRMClientWithoutFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/winrm/WinRMWithFIPSTest.java
  src/test/java/hudson/plugins/ec2/win/winrm/WinRMWithoutFIPSTest.java
Labels: enhancement
